name: Publish GH - Pages

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Add WASM Tools (for AOT compilation)
        run: dotnet workload install wasm-tools
      - name: Build
        run: dotnet publish SpongeBobCase.Blazor -c Release
      - name: Update gitattributes
        run: mv SpongeBobCase.Blazor/bin/Release/net6.0/publish/wwwroot/gitattributes SpongeBobCase.Blazor/bin/Release/net6.0/publish/wwwroot/.gitattributes
      - name: Move Blazor Output into Place
        run: mv SpongeBobCase.Blazor/bin/Release/net6.0/publish/wwwroot toPublish/
      - name: Make js subdirectory
        run: mkdir toPublish/JS
      - name: Move Javascript OutPut into place
        run: cp SpongeBobCase.Js/* toPublish/JS/
      - name: Make elm Dir
        run: mkdir toPublish/elm
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: cd SpongeBobCase.Elm && elm make ./src/Main.elm --output ../toPublish/elm/index.html
      - run: cd

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: toPublish